# Generated by Django 5.2 on 2025-04-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_messageee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messageee',
        ),
    ]
