# Generated by Django 5.2 on 2025-04-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_message_audio_file_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('message', 'message'), ('audio', 'audio')], default='message', max_length=25),
        ),
    ]
