# Generated by Django 5.2 on 2025-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0009_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('message', 'message'), ('audio', 'audio'), ('file', 'file')], default='message', max_length=25),
        ),
    ]
