# Generated by Django 5.2 on 2025-05-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0012_audiomessage_filemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
