# Generated by Django 5.2 on 2025-05-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0013_remove_message_audio_file_remove_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
