# Generated by Django 5.2.7 on 2025-11-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('file', 'File')], default='text', max_length=25),
        ),
    ]
