# Generated by Django 5.2.7 on 2025-11-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0002_alter_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/chat_files/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=255)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_message', to='message.message')),
            ],
        ),
    ]
