# Generated by Django 5.2.7 on 2025-11-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user1_deleted_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2_deleted_chat',
            field=models.BooleanField(default=False),
        ),
    ]
