"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ

env = environ.Env()
environ.Env.read_env(env_file=BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4300",
    "https://localhost:4300",
    "http://localhost:4200",
    "https://localhost:4200",
    "https://proton.shalabyziad94.workers.dev",
    "https://desktop-97l1ctr.tailc9493e.ts.net",
]

AUTH_USER_MODEL = "auth_app.User"

# Application definition

INSTALLED_APPS = [
    # Third-party apps
    "unfold",
    "daphne",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "channels",
    "corsheaders",
    "django_cleanup.apps.CleanupConfig",

    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local apps
    "auth_app",
    "chat",
    "message",
    "audio_message",
    "file_message",
    "text_message",
]

MIDDLEWARE = [
    "auth_app.authentication.CSRFMiddlewareWithJWT",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": env("POSTGRES_DB"),
#         "USER": env("POSTGRES_USER"),
#         "PASSWORD": env("POSTGRES_PASSWORD"),
#         "HOST": env("POSTGRES_HOST"),
#         "PORT": env("POSTGRES_PORT"),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'auth_app.validators.StrongPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "auth_app.authentication.CookieJWTAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    "DEFAULT_THROTTLE_RATES": {
        "main": "120/min",
        "second": "12/hour",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Authentication API",
    "DESCRIPTION": "Authentication API Documentation",
    "VERSION": "1.0.0",
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),       # Access token validity duration
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),        # Refresh token validity duration
    "ROTATE_REFRESH_TOKENS": True,                      # If True, issues a new refresh token with every refresh
    "BLACKLIST_AFTER_ROTATION": True,                   # If using token blacklisting
    "ALGORITHM": "HS256",                               # Signing algorithm
    "SIGNING_KEY": SECRET_KEY,                          # Secret key for signing tokens
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),                   # Header format: Authorization: Bearer <token>
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
}

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env("GOOGLE_CLIENT_ID")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env("GOOGLE_CLIENT_SECRET")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

FRONTEND_URL = "https://proton.shalabyziad94.workers.dev/"

# Jwt Cookies
SAMESITE = 'None'
HTTPONLY = True
SECURE = True
ACCESS_MAX_AGE = SIMPLE_JWT.get('ACCESS_TOKEN_LIFETIME')
REFRESH_MAX_AGE = SIMPLE_JWT.get('REFRESH_TOKEN_LIFETIME')
COOKIE_PATH = '/'

# CSRF
CSRF_COOKIE_NAME = "csrftoken"         # Default cookie name
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_SECURE = True              # HTTPS only in production
CSRF_COOKIE_HTTPONLY = False           # Must be False so JavaScript can read the cookie
CSRF_COOKIE_SAMESITE = "None"          # Or "Strict" 
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

import re

CSRF_EXEMPT_URL_PATTERNS = [
	# Auth
    re.compile(r"^/api/auth/register/?$"),
    re.compile(r"^/api/auth/login/?$"),
    re.compile(r"^/api/auth/google-login/?$"),
    
    re.compile(r"^/api/auth/token/refresh/?$"),
    re.compile(r"^/api/auth/token/verify/?$"),
    
    re.compile(r"^/api/auth/password-reset-link/?$"),
    re.compile(r"^/api/auth/password-reset-confirm/?$"),
    
    re.compile(r"^/api/auth/verify-email/?$"),
    re.compile(r"^/api/auth/resend-verification-email/?$"),
    
    re.compile(r"^/api/auth/logout/?$"),
]


CELERY_BROKER_URL = "redis://192.168.1.9:6379/0"

CELERY_RESULT_BACKEND = "redis://192.168.1.9:6379/1"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE


from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


from django.urls import reverse_lazy
UNFOLD = {
    "SITE_TITLE": "Proton Admin",
    "SITE_HEADER": "Proton",
    "SITE_SUBHEADER": "Administration",
    "SITE_SYMBOL": "dashboard",
    
    "STYLES": [
        "/static/unfold/css/unfold-custom.css",
    ],
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,

        "navigation": [
            {
                "title": "Authentication",
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy(
                            "admin:auth_app_user_changelist"
                        ),
                    },
                    {
                        "title": "Groups",
                        "icon": "groups",
                        "link": reverse_lazy(
                            "admin:auth_group_changelist"
                        ),
                    },
                ],
            },

            {
                "title": "Chat",
                "items": [
                    {
                        "title": "Chats",
                        "icon": "chat",
                        "link": reverse_lazy(
                            "admin:chat_chat_changelist"
                        ),
                    },
                    {
                        "title": "Chat Participants",
                        "icon": "group",
                        "link": reverse_lazy(
                            "admin:chat_chatparticipant_changelist"
                        ),
                    },
                    {
                        "title": "Messages",
                        "icon": "message",
                        "link": reverse_lazy(
                            "admin:message_message_changelist"
                        ),
                    },
                    {
                        "title": "Text Messages",
                        "icon": "text_fields",
                        "link": reverse_lazy(
                            "admin:text_message_textmessage_changelist"
                        ),
                    },
                    {
                        "title": "Audio Messages",
                        "icon": "mic",
                        "link": reverse_lazy(
                            "admin:audio_message_audiomessage_changelist"
                        ),
                    },
                    {
                        "title": "File Messages",
                        "icon": "attach_file",
                        "link": reverse_lazy(
                            "admin:file_message_filemessage_changelist"
                        ),
                    },
                ],
            },

            {
                "title": "Security",
                "items": [
                    {
                        "title": "Outstanding Tokens",
                        "icon": "key",
                        "link": reverse_lazy(
                            "admin:token_blacklist_outstandingtoken_changelist"
                        ),
                    },
                    {
                        "title": "Blacklisted Tokens",
                        "icon": "block",
                        "link": reverse_lazy(
                            "admin:token_blacklist_blacklistedtoken_changelist"
                        ),
                    },
                ],
            },
        ],
    },
}