# Generated by Django 5.2.7 on 2025-11-12 09:34

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Just landed here… where’s the fun button?', max_length=450),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=auth_app.models.user_image_upload_path),
        ),
    ]
