# Generated by Django 5.2.7 on 2025-11-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_bio_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Good talks make good days.', max_length=450),
        ),
    ]
